# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=200)),
                ('pub_year', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('pub_title', models.CharField(max_length=200)),
                ('issn', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
