# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISHAR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_access',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_add',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_mod',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='extra',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='journal_abbr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='lib_cat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='short_title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='issn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='item_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='journal',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='journal',
            name='summary',
            field=models.CharField(max_length=255),
        ),
    ]
