# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ISHAR', '0003_auto_20171027_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ISHAR.Category'),
        ),
    ]
