# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISHAR', '0004_auto_20171027_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
